apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: crd-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: example.com/v1
    resource: pings
  childResources:
    - apiVersion: apiextensions.k8s.io/v1beta1
      resource: customresourcedefinitions
      updateStrategy:
        method: InPlace
  hooks:
    sync:
      webhook:
        url: http://192.168.1.15:8080/sync
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: ping-pong-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: example.com/v1
    resource: pings
  childResources:
    - apiVersion: example.com/v1
      resource: pongs
      updateStrategy:
        method: InPlace
  hooks:
    sync:
      webhook:
        url: http://192.168.1.15:8081/sync
