apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: ping-pong-controller
spec:
  resources:
  - apiVersion: example.com/v1
    resource: pings
  attachments:
  - apiVersion: example.com/v1
    resource: pongs
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://192.168.1.15:8080/sync
