apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: ping-pong-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: example.com/v1
    resource: pings
  childResources:
    - apiVersion: example.com/v1
      resource: pongs
      updateStrategy:
        method: Recreate
  hooks:
    sync:
      webhook:
        url: http://sample-controller-js.metacontroller/sync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-controller-js
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-controller-js
  template:
    metadata:
      labels:
        app: sample-controller-js
    spec:
      containers:
        - name: controller
          image: quay.io/shovanmaity/metacontroller-by-example:js-v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: sample-controller-js
  namespace: metacontroller
spec:
  selector:
    app: sample-controller-js
  ports:
    - port: 80
      targetPort: 8080
